services:
  postgres:
    image: 'postgres:17.4'
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=postgres'
    ports:
      - '5432:5432'
    labels:
      org.springframework.boot.service-connection: postgres
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10
